from typing import Protocol, Optional, Dict, Any

class ISpamRepository(Protocol):
    async def add_record(self, user_id: int, chat_id: int, spam_type: str, content_hash: str = None) -> None: ...
    async def count_recent(self, user_id: int, chat_id: int, spam_type: str, window_seconds: int, content_hash: str = None) -> int: ...
    async def clear_user(self, user_id: int, chat_id: int) -> None: ...

class IWhitelistRepository(Protocol):
    async def is_whitelisted(self, user_id: int, chat_id: int) -> bool: ...
    async def add(self, user_id: int, chat_id: int, added_by: int = None) -> bool: ...
    async def remove(self, user_id: int, chat_id: int) -> bool: ...

class IChatSettingsRepository(Protocol):
    async def get(self, chat_id: int) -> Dict[str, Any]: ...
    async def set(self, chat_id: int, key: str, value: int) -> bool: ...
